/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/log-ride`; params?: Router.UnknownInputParams; } | { pathname: `/review-composer`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ranks` | `/ranks`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/tutorial/howitworks`; params?: Router.UnknownInputParams; } | { pathname: `/tutorial`; params?: Router.UnknownInputParams; } | { pathname: `/coaster/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/park/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/log-ride`; params?: Router.UnknownOutputParams; } | { pathname: `/review-composer`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/ranks` | `/ranks`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/tutorial/howitworks`; params?: Router.UnknownOutputParams; } | { pathname: `/tutorial`; params?: Router.UnknownOutputParams; } | { pathname: `/coaster/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/park/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/log-ride${`?${string}` | `#${string}` | ''}` | `/review-composer${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/ranks${`?${string}` | `#${string}` | ''}` | `/ranks${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/tutorial/howitworks${`?${string}` | `#${string}` | ''}` | `/tutorial${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/log-ride`; params?: Router.UnknownInputParams; } | { pathname: `/review-composer`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ranks` | `/ranks`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/tutorial/howitworks`; params?: Router.UnknownInputParams; } | { pathname: `/tutorial`; params?: Router.UnknownInputParams; } | `/coaster/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/park/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/coaster/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/park/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
